### ISSUE TITLE
Safari 100vh + Target Safari

### ISSUE THREAD

**Issue by rootEnginear** [rootEnginear/my-common-patterns#12]
```css
@supports (-webkit-touch-callout: none) {
    body {
        min-height: -webkit-fill-available;
    }
}
```
