### ISSUE TITLE
Default Font Stack

### ISSUE THREAD

**Issue by rootEnginear** [rootEnginear/my-common-patterns#14]
## Sans-serif

```css
body {
  font-family: FONT_NAME, system-ui, -apple-system,
    BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell",
    "Fira Sans", "Droid Sans", "Helvetica Neue", "Segoe UI Emoji",
    "Apple Color Emoji", "Noto Color Emoji", sans-serif;
}
```

## Monospace

```css
code {
  font-family: FONT_NAME, Consolas,
    "Andale Mono WT", "Andale Mono", "Lucida Console", "Lucida Sans Typewriter",
    "DejaVu Sans Mono", "Bitstream Vera Sans Mono", "Liberation Mono", "Nimbus Mono L",
    Monaco, "Courier New", Courier, "Segoe UI Emoji", "Apple Color Emoji",
    "Noto Color Emoji", monospace;
}
```

## Tips
- เอาฟอนต์ไทยขึ้นก่อนฟอนต์ละตินเสมอ **แต่ถ้าเป็นโค้ด** ให้เอาละตินขึ้นก่อนไทย (ฟอนต์ไทย 99.99% ไม่ใช่ Monospace เวลาหาตัวละตินไม่เจอจะได้ Fallback ไปหาภาษาไทย)
