### ISSUE TITLE
ตัดลิงก์ไม่ให้ overflow

### ISSUE THREAD

**Issue by rootEnginear** [rootEnginear/my-common-patterns#18]
```css
a {
  overflow-wrap: break-word;
  word-wrap: break-word;
  word-break: break-word;
  hyphens: none;
}
```
ลิงก์ยาวๆ ที่เป็นพวก url อาจจะ overflow container ได้, declarations ข้างบนจะทำให้มันตัดขึ้นบรรทัดใหม่ได้
