### ISSUE TITLE
Lock Scroll แต่ไม่ซ่อน Scrollbar

### ISSUE THREAD

**Issue by rootEnginear** [rootEnginear/my-common-patterns#19]
```scss
html.lock-body-scroll {
  position: fixed;
  overflow-y: scroll;
  width: 100%;

  > body {
    overflow-y: hidden;
  }
}
```
จะทำให้เรา scroll เว็บไม่ได้ แต่จะยังโชว์ scrollbar อยู่ เหมาะกับกรณีที่ไม่อยากให้ layout shift
