### ISSUE TITLE
ซ่อน Scrollbar

### ISSUE THREAD

**Issue by rootEnginear** [rootEnginear/my-common-patterns#20]
```css
.scrollbar-none {
  scrollbar-width: none;
}

.scrollbar-none::-webkit-scrollbar {
  display: none;
}
```
